gofitt/gofitt/src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * Utilisateur
 *
 * @ORM\Table(name="utilisateur")
 * @ORM\Entity
 */
class Utilisateur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $Utilisateur_Id;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Mdp;

    /**
     * @ORM\Column(type="string", length=22)
     */
    private $Datedenaissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Region;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Numero;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Role;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $Sexe;
    /**
     * @ORM\Column(type="string", length=7)
     */
    private $question;
    /**
     * @ORM\Column(type="string", length=7)
     */
    private $reponse;

    public function getUtilisateur_Id(): ?int
    {
        return $this->Utilisateur_Id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getMdp(): ?string
    {
        return $this->Mdp;
    }

    public function setMdp(string $Mdp): self
    {
        $this->Mdp = $Mdp;

        return $this;
    }

    public function getDatedenaissance(): ?string
    {
        return $this->Datedenaissance;
    }

    public function setDatedenaissance(string $Datedenaissance): self
    {
        $this->Datedenaissance = $Datedenaissance;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->Region;
    }

    public function setRegion(string $Region): self
    {
        $this->Region = $Region;

        return $this;
    }

    public function getNumero(): ?string
    {
        return $this->Numero;
    }

    public function setNumero(string $Numero): self
    {
        $this->Numero = $Numero;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->Role;
    }

    public function setRole(string $Role): self
    {
        $this->Role = $Role;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->Sexe;
    }

    public function setSexe(string $Sexe): self
    {
        $this->Sexe = $Sexe;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getQuestion()
    {
        return $this->question;
    }

    /**
     * @param mixed $question
     * @return Utilisateur
     */
    public function setQuestion($question)
    {
        $this->question = $question;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getReponse()
    {
        return $this->reponse;
    }

    /**
     * @param mixed $reponse
     * @return Utilisateur
     */
    public function setReponse($reponse)
    {
        $this->reponse = $reponse;
        return $this;
    }

}

gofitt/gofitt/src/Controller/UtilisateurController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Utilisateur;
use App\Form\AjouterType;
use App\Form\UtilisateurType;
use App\Repository\UtilisateurRepository;

use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use Symfony\Component\Routing\Annotation\Route;


class UtilisateurController extends AbstractController
{
    /**
     * @Route("/utilisateur", name="app_utilisateur")
     */
    public function index(): Response
    {
        return $this->render('utilisateur/index.html.twig', [
            'controller_name' => 'UtilisateurController',
        ]);
    }
    /**
     * @Route("/utilisateur/shop", name="app_utilisateur/shop")
     */
    public function index1(): Response
    {
        return $this->render('base-back.html.twig', [
            'controller_name' => 'UtilisateurController',
        ]);
    }
    /**
     * @param Request $request
     * @return Response
     * @Route ("Utilisateur/Ajout",name="ajouter")
     */
        function Ajouter(Request $request)
        {
            $utilisateur= new utilisateur();
            $form = $this->createForm(AjouterType::class,$utilisateur);
            $form ->add('Ajouter',SubmitType::class);
            $form->handleRequest($request);
            if($form->isSubmitted() && $form->isValid()) {
                $em=$this->getDoctrine()->getManager();
                $em->persist($utilisateur);
                $em->flush();
                return $this->render('utilisateur/connection.html.twig');
            }



            return $this->render('utilisateur/Ajouter.html.twig', ['fa' => $form->createView()]);

        }

    /**
     * @param UtilisateurRepository $repository
     * @Route ("AfficheU",name="Affiche")
     */
    public function Affiche( UtilisateurRepository $repository)
    {
        $utilisateur = $repository->findAll();
        return $this->render('utilisateur/Afficher.html.twig', [
            'utilisateur' => $utilisateur
        ]);
    }
    /**
* @Route ("/Supprimer/{id_utilisateur}",name="supp")
*/
    public function Supprimer($id_utilisateur) {
        $utilisateur=$this->getDoctrine()->getRepository(Utilisateur::class)->find($id_utilisateur);
        $em=$this->getDoctrine()->getManager();
        $em->remove($utilisateur);
        $em->flush();
        return $this->redirectToRoute('Affiche');

    }

    /**
     * @Route ("/Modifier/{id_utilisateur}",name="mod")
     */
    public function Modifier ( Request $request  ,UtilisateurRepository $repository , $id_utilisateur )  {
        $utilisateur=$repository->find($id_utilisateur);

        $form = $this->createForm(AjouterType::class,$utilisateur);
        $form ->add('Modifier',SubmitType::class);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            $em=$this->getDoctrine()->getManager();

            $em->flush();

            return $this->redirectToRoute('Affiche');
        }

        return $this->render('utilisateur/modifier.html.twig', ['f' => $form->createView()]);
    }


    public function login()
    {
        if ($this->getUser()) {
            return $this->redirectToRoute('afficher');
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }
}

gofitt/gofitt/templates/utilisateur/Afficher.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Gestion des utilisateurs{% endblock %}

{% block body %}
    <style>
        table {
            border-collapse: collapse;
        }
        td,
        th {
            border: 1px solid black;
            border-collapse: collapse;
        }
    </style>
    <script src="https://use.fontawesome.com/49b98aaeb5.js"></script>
    <!-- End -->
    <center>
    <i class="fa fa-user fa-3x" aria-hidden="true" style="color:#6495ed"></i>
   <FONT face="Helvetica" size="8" color="#6495ed" >    Tables des utilisateurs
       <br> </FONT></center>

    <table border="1"    >

        <tr>
            <th><center> <FONT face="Helvetica" color="#6495ed" > ID UTILISATEUR </FONT> </center></th>
            <th> <center> <FONT face="Helvetica" color="#6495ed"> NOM  </FONT> </center></th>
            <th> <center> <FONT face="Helvetica" color="#6495ed"> PRENOM </FONT> </center> </th>
            <th> <center> <FONT face="Helvetica" color="#6495ed"> EMAIL</FONT> </center> </th>
            <th> <center> <FONT face="Helvetica" color="#6495ed"> MOT DE PASSE </FONT> </center> </th>
            <th> <center> <FONT face="Helvetica" color="#6495ed"> DATE DE NAISSANCE </FONT> </center> </th>
            <th> <center> <FONT face="Helvetica" color="#6495ed"> ROLE  </FONT> </center> </th>
            <th> <center> <FONT face="Helvetica" color="#6495ed"> SEXE </FONT></center> </th>
            <th><center>  <FONT face="Helvetica" color="#6495ed">REGION </FONT></center> </th>
            <th><center>  <FONT face="Helvetica" color="#6495ed"> ADRESSE </FONT></center> </th>
            <th><center> <FONT face="Helvetica" color="#6495ed">NUMERO </FONT> </center></th>
            <th> <center><FONT face="Helvetica" color="#6495ed"> ACTION </FONT></center></th>
        </tr>
        <tr {% for u in utilisateur  %}>
            <td align="center" > {{u.Utilisateur_Id}}</td>
            <td align="center" > {{u.nom }}</td>
            <td align="center" > {{u.prenom}} </td>
            <td align="center" > {{u.email }}</td>
            <td align="center" > {{u.mdp}} </td>
            <td align="center" > {{u.datedenaissance}}</td>
            <td align="center" > {{u.role}}</td>
            <td align="center" > {{u.sexe }}</td>
            <td align="center" > {{u.region}}</td>
            <td align="center" > {{u.adresse}} </td>
            <td align="center" > {{u.numero}}</td>
            <td align="center" width="8" height="8">
                <script src="https://use.fontawesome.com/49b98aaeb5.js"></script>
            <a href="{{ path('supp',{'id_utilisateur': u.Utilisateur_Id}) }}">  <i class="fa fa-trash fa-1x" aria-hidden="true" style="color:brown"></i>  Supprimer   </a> <br>
                <a href="{{ path('mod', {'id_utilisateur': u.Utilisateur_Id}) }}"> <i class="fa fa-edit fa-1x" aria-hidden="true" style="color:brown"></i>   Modifier   </a> </td>
        </tr {%endfor %}>
       </center>
    </table>


{% endblock %}

gofitt/gofitt/templates/utilisateur/Ajouter.html.twig
{% extends 'base-front.html.twig' %}

    {% block body %}

        <div class="breadcrumb-section breadcrumb-bg-color--golden">
            <div class="breadcrumb-wrapper">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <h3 class="breadcrumb-title">S'inscrire</h3>
                            <div class="breadcrumb-nav breadcrumb-nav-color--black breadcrumb-nav-hover-color--golden">
                                <nav aria-label="breadcrumb">
                                    <ul>
                                        <li><a href="index.html">Accueil</a></li>
                                        <li><a href="index.html">Se connecter</a></li>
                                        <li class="active" aria-current="page">S'inscrire</li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            {{ form_start(fa) }}
            <center><h1>S'inscrire</h1></center>
            <br>
            <div class="row">
                <form class="col s12">

                    <div class="row">
                        <div class="input-field col s6">
                            {{ form_label(fa.Nom) }}
                            {{ form_widget(fa.Nom) }}
                        </div>
                        <div class="input-field col s6">
                            {{ form_label(fa.Prenom) }}
                            {{ form_widget(fa.Prenom) }}
                        </div>

                    </div>

                    <div class="row">
                        <div class="input-field col s6">
                            {{ form_label(fa.Email) }}
                            {{ form_widget(fa.Email) }}
                        </div>
                        <div class="input-field col s6">
                            {{ form_label(fa.Sexe) }}
                            {{ form_widget(fa.Sexe) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s6">
                            {{ form_label(fa.Adresse) }}
                            {{ form_widget(fa.Adresse) }}
                        </div>
                        <div class="input-field col s6">
                            {{ form_label(fa.Region) }}
                            {{ form_widget(fa.Region) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s6">
                            {{ form_label(fa.Role) }}
                            {{ form_widget(fa.Role) }}
                        </div>
                        <div class="input-field col s6">
                            {{ form_label(fa.Mdp) }}
                            {{ form_widget(fa.Mdp) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s6">
                            {{ form_label(fa.question) }}
                            {{ form_widget(fa.question) }}
                        </div>
                        <div class="input-field col s6">
                            {{ form_label(fa.reponse) }}
                            {{ form_widget(fa.reponse) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s6">
                            {{ form_label(fa.Numero) }}
                            {{ form_widget(fa.Numero) }}
                        </div>

                    <div class="input-field col s6">
                        {{ form_label(fa.Datedenaissance )  }}
                        {{ form_widget(fa.Datedenaissance)}}
                    </div>
            </div>
                    <br>
                    <br>
                    <br><br>
                    <br>

                    <center>{{ form_end(fa) }}</center>
                    <br>
                    <br>
                    <br><br>
                    <br>

                </form>


            </div>

        </div>
    {% endblock %}

gofitt/gofitt/templates/utilisateur/connection.html.twig
{% extends 'base-front.html.twig' %}

    {% block body %}
        <div class="breadcrumb-section breadcrumb-bg-color--golden">
            <div class="breadcrumb-wrapper">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <h3 class="breadcrumb-title">Se connecter</h3>
                            <div class="breadcrumb-nav breadcrumb-nav-color--black breadcrumb-nav-hover-color--golden">
                                <nav aria-label="breadcrumb">
                                    <ul>
                                        <li><a href="index.html">Accueil</a></li>
                                        <li class="active" aria-current="page">Se connecter</li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    {% endblock %}

gofitt/gofitt/templates/utilisateur/index.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Hello UtilisateurController!{% endblock %}

{% block body %}





{% endblock %}

gofitt/gofitt/templates/utilisateur/modifier.html.twig
{% extends 'base-front.html.twig' %}

    {% block body %}

        <div class="breadcrumb-section breadcrumb-bg-color--golden">
            <div class="breadcrumb-wrapper">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <h3 class="breadcrumb-title">Mon Compte</h3>
                            <div class="breadcrumb-nav breadcrumb-nav-color--black breadcrumb-nav-hover-color--golden">
                                <nav aria-label="breadcrumb">
                                    <ul>
                                        <li><a href="index.html">Accueil</a></li>
                                        <li class="active" aria-current="page">Mon Compte</li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            {{ form_start(f) }}
            <center><h1>Mon Compte </h1></center>
            <br>
            <div class="row">
                <form class="col s12">

                    <div class="row">
                        <div class="input-field col s6">
                            {{ form_label(f.Nom) }}
                            {{ form_widget(f.Nom) }}
                        </div>
                        <div class="input-field col s6">
                            {{ form_label(f.Prenom) }}
                            {{ form_widget(f.Prenom) }}
                        </div>

                    </div>

                    <div class="row">
                        <div class="input-field col s6">
                            {{ form_label(f.Email) }}
                            {{ form_widget(f.Email) }}
                        </div>
                        <div class="input-field col s6">
                            {{ form_label(f.Sexe) }}
                            {{ form_widget(f.Sexe) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s6">
                            {{ form_label(f.Adresse) }}
                            {{ form_widget(f.Adresse) }}
                        </div>
                        <div class="input-field col s6">
                            {{ form_label(f.Region) }}
                            {{ form_widget(f.Region) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s6">
                            {{ form_label(f.Role) }}
                            {{ form_widget(f.Role) }}
                        </div>
                        <div class="input-field col s6">
                            {{ form_label(f.Mdp) }}
                            {{ form_widget(f.Mdp) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s6">
                            {{ form_label(f.question) }}
                            {{ form_widget(f.question) }}
                        </div>
                        <div class="input-field col s6">
                            {{ form_label(f.reponse) }}
                            {{ form_widget(f.reponse) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s6">
                            {{ form_label(f.Numero) }}
                            {{ form_widget(f.Numero) }}
                        </div>

                        <div class="input-field col s6">
                            {{ form_label(f.Datedenaissance )  }}
                            {{ form_widget(f.Datedenaissance)}}
                        </div>
                    </div>
                    <br>
                    <br>
                    <br><br>
                    <br>

                    <center>{{ form_end(f) }}</center>
                    <br>
                    <br>
                    <br><br>
                    <br>

                </form>


            </div>

        </div>
    {% endblock %}